/dua_tf_server:
  ros__parameters:
    fixed_frame: map
    pose_period: 50
    source_frames:
      - base_link
    target_frames:
      - map
    use_sim_time: false

/lio_sam:
  ros__parameters:
    autostart: true
    cpu:
      image_projection: -1
      feature_extraction: -1
      map_optimization: -1
      loop_closure: -1
    features:
      leaf_size: 0.2
      edge_threshold: 1.0
      surface_threshold: 0.1
      segments_per_scan: 6
      max_edge_per_segments: 20
    frames:
      map: "map"
      odom: "odom"
      base_link: "base_link"
    lidar:
      range:
        min: 0.5
        max: 100.0
      scan:
        vertical: 64
        horizontal: 2000
    mapping:
      leaf_size:
        edge: 0.2
        surface: 0.2
      min:
        edge: 10
        surface: 100
      cores: 8
      surrounding_keyframe:
        density: 2.0
        search_radius: 100.0
        adding_threshold:
          angle: 0.2
          distance: 1.0
      history_keyframe:
        search_num: 100
        search_radius: 30.0
        search_time_diff: 1.0
        fitness_score: 0.3
      global_map:
        search_radius: 100.0
        pose_density: 1.0
        leaf_size: 0.01
      rpy_weight: 0.1
    tf:
      publish: false
    use_sim_time: false
    verbose: false

/ekf_local:
  ros__parameters:
    autostart: true
    use_sim_time: false
    verbose: false
    worker_cpu: -1

    filter_type: ekf

    # Only for ukf
    # params:
    #   alpha: 0.001
    #   beta: 2.0
    #   kappa: 0.0

    smooth_lagged_data: false
    history_length: 0.1
    process_noise_covariance: [0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001]
    dynamic_process_noise_covariance: false
    initial_estimate_covariance: [0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01]
    predict_to_current_time: false

    map_frame: map
    world_frame: odom
    odom_frame: odom
    base_frame: base_link
    base_footprint_frame: base_link
    base_link_frame: base_link
    base_link_frame_output: base_link

    x_correction: 1.0
    y_correction: 1.0

    publish_tf: true
    publish_acceleration: false
    permit_corrected_publication: false

    tf_time_offset: 0.0
    tf_timeout: 0.0
    frequency: 30.0
    sensor_timeout: 0.1

    initial_state: [0.0, 0.0, 0.0,    # x, y, z
                    0.0, 0.0, 0.0,    # R, P ,Y
                    0.0, 0.0, 0.0,    # vx, vy, vz
                    0.0, 0.0, 0.0,    # vR, vP, vY
                    0.0, 0.0, 0.0]    # ax, ay, az
    correct_state: [false, false, false,
                    false, false, false]
    acceleration_limits: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    acceleration_gains: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    deceleration_limits: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    deceleration_gains: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    gravitational_acceleration: 9.81

    # cmd_vel | v_x, v_y, v_yaw
    control:
      topic_name: /cmd_vel
      config: [true, true, false, false, false, true]
      use: false
      stamped: false
      timeout: 0.2

    # IMU with orientation | gyroscope, accelerometer
    imu0:
      topic_name: /kitti/imu
      config: [false, false, false,        # [x_pos   , y_pos    , z_pos,
               false, false, false,        #  roll    , pitch    , yaw,
               false, false, false,        #  x_vel   , y_vel    , z_vel,
               true,  true,  true,         #  roll_vel, pitch_vel, yaw_vel,
               true,  true,  true]         #  x_accel , y_accel  , z_accel]
      differential: false
      relative: false
      dynamic_tf: false
      remove_gravitational_acceleration: true

/ekf_global:
  ros__parameters:
    autostart: true
    use_sim_time: false
    verbose: false
    worker_cpu: 1

    filter_type: ekf

    # Only for ukf
    # params:
    #   alpha: 0.001
    #   beta: 2.0
    #   kappa: 0.0

    smooth_lagged_data: false
    history_length: 0.1
    process_noise_covariance: [0.000001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0, 0.000001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.001]
    dynamic_process_noise_covariance: false
    initial_estimate_covariance: [0.0001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0, 0.0001,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.01]
    predict_to_current_time: false

    map_frame: map
    world_frame: map
    odom_frame: odom
    base_frame: base_link
    base_footprint_frame: base_link
    base_link_frame: base_link
    base_link_frame_output: base_link

    x_correction: 1.0
    y_correction: 1.0

    publish_tf: true
    publish_acceleration: false
    permit_corrected_publication: false

    tf_time_offset: 0.0
    tf_timeout: 0.0
    frequency: 30.0
    sensor_timeout: 0.1

    initial_state: [0.0, 0.0, 0.0,          # x, y, z
                    0.0, 0.0, 0.0,          # R, P ,Y
                    0.0, 0.0, 0.0,          # vx, vy, vz
                    0.0, 0.0, 0.0,          # vR, vP, vY
                    0.0, 0.0, 0.0]          # ax, ay, az
    correct_state: [true, true, false,
                    false, false, true]
    acceleration_limits: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    acceleration_gains: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    deceleration_limits: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    deceleration_gains: [1.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    gravitational_acceleration: 9.81

    # Go2 cmd_vel | v_x, v_y, v_yaw
    control:
      topic_name: /cmd_vel
      config: [true, true, false, false, false, true]
      use: false
      stamped: false
      timeout: 0.2

    # GPS pose | x, y
    pose0:
      topic_name: /lio_sam/map_optimization/pose
      config: [true, true, true,           # [x_pos   , y_pos    , z_pos,
               true, true, true,           #  roll    , pitch    , yaw,
               false, false, false,        #  x_vel   , y_vel    , z_vel,
               false, false, false,        #  roll_vel, pitch_vel, yaw_vel,
               false, false, false]        #  x_accel , y_accel  , z_accel]
      differential: false
      relative: false
      dynamic_tf: false

    # IMU with orientation | gyroscope, accelerometer
    imu0:
      topic_name: /kitti/imu
      config: [false, false, false,        # [x_pos   , y_pos    , z_pos,
               false, false, false,        #  roll    , pitch    , yaw,
               false, false, false,        #  x_vel   , y_vel    , z_vel,
               true,  true,  true,         #  roll_vel, pitch_vel, yaw_vel,
               true,  true,  true]         #  x_accel , y_accel  , z_accel]
      differential: false
      relative: false
      dynamic_tf: false
      remove_gravitational_acceleration: true
